{% set name = "csv2table" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/csv2table-{{ version }}.tar.gz
  sha256: 91544b3178f4dfd6ba1884e0dca02fc728256ecd12d05dfc8f7c67565601c3ac

build:
  number: 0
  noarch: python
  entry_points:
    - csv2table = csv2table.csv2table:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - terminaltables

test:
  imports:
    - csv2table
  commands:
    - pip check
    - csv2table --help
  requires:
    - pip

about:
  home: https://github.com/ickc/csv2table
  summary: CSV to Grid Table in Markdown
  license: GPL-3.0-or-later
  license_file: LICENCE

extra:
  recipe-maintainers:
    - ickc
